<a href="https://colab.research.google.com/github/violet-rgb/ICT_DSA/blob/main/Data_acquisition_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Load SpaceX Launch Data from API
● Use https://api.spacexdata.com/v4/launches
● Extract relevant columns: name, date_utc, success, details, rocket

In [1]:
import requests
url = " https://api.spacexdata.com/v4/launches"
data = requests.get(url).json()
print(type(data))

<class 'list'>

In [2]:
print(data[0])

{'fairings': {'reused': False, 'recovery_attempt': False, 'recovered': False, 'ships': []}, 'links': {'patch': {'small': 'https://images2.imgbox.com/94/f2/NN6Ph45r_o.png', 'large': 'https://images2.imgbox.com/5b/02/QcxHUb5V_o.png'}, 'reddit': {'campaign': None, 'launch': None, 'media': None, 'recovery': None}, 'flickr': {'small': [], 'original': []}, 'presskit': None, 'webcast': 'https://www.youtube.com/watch?v=0a_00nJ_Y88', 'youtube_id': '0a_00nJ_Y88', 'article': 'https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html', 'wikipedia': 'https://en.wikipedia.org/wiki/DemoSat'}, 'static_fire_date_utc': '2006-03-17T00:00:00.000Z', 'static_fire_date_unix': 1142553600, 'net': False, 'window': 0, 'rocket': '5e9d0d95eda69955f709d1eb', 'success': False, 'failures': [{'time': 33, 'altitude': None, 'reason': 'merlin engine failure'}], 'details': 'Engine failure at 33 seconds and loss of vehicle', 'crew': [], 'ships': [], 'capsules': [], 'payloads': ['5eb0e4b5b6c3bb0006eeb1e1'], 'launchpad': '5e9e4502f5090995de566f86', 'flight_number': 1, 'name': 'FalconSat', 'date_utc': '2006-03-24T22:30:00.000Z', 'date_unix': 1143239400, 'date_local': '2006-03-25T10:30:00+12:00', 'date_precision': 'hour', 'upcoming': False, 'cores': [{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}], 'auto_update': True, 'tbd': False, 'launch_library_id': None, 'id': '5eb87cd9ffd86e000604b32a'}

In [3]:
import pandas as pd
df = pd.DataFrame(data)

In [5]:
print(df.head())
print(df.columns)

                                            fairings  \
0  {'reused': False, 'recovery_attempt': False, '...
1  {'reused': False, 'recovery_attempt': False, '...
2  {'reused': False, 'recovery_attempt': False, '...
3  {'reused': False, 'recovery_attempt': False, '...
4  {'reused': False, 'recovery_attempt': False, '...

                                               links  \
0  {'patch': {'small': 'https://images2.imgbox.co...
1  {'patch': {'small': 'https://images2.imgbox.co...
2  {'patch': {'small': 'https://images2.imgbox.co...
3  {'patch': {'small': 'https://images2.imgbox.co...
4  {'patch': {'small': 'https://images2.imgbox.co...

       static_fire_date_utc  static_fire_date_unix    net  window  \
0  2006-03-17T00:00:00.000Z           1.142554e+09  False     0.0
1                      None                    NaN  False     0.0
2                      None                    NaN  False     0.0
3  2008-09-20T00:00:00.000Z           1.221869e+09  False     0.0
4                      None                    NaN  False     0.0

                     rocket success  \
0  5e9d0d95eda69955f709d1eb   False
1  5e9d0d95eda69955f709d1eb   False
2  5e9d0d95eda69955f709d1eb   False
3  5e9d0d95eda69955f709d1eb    True
4  5e9d0d95eda69955f709d1eb    True

                                            failures  \
0  [{'time': 33, 'altitude': None, 'reason': 'mer...
1  [{'time': 301, 'altitude': 289, 'reason': 'har...
2  [{'time': 140, 'altitude': 35, 'reason': 'resi...
3                                                 []
4                                                 []

                                             details  ...  \
0   Engine failure at 33 seconds and loss of vehicle  ...
1  Successful first stage burn and transition to ...  ...
2  Residual stage 1 thrust led to collision betwe...  ...
3  Ratsat was carried to orbit on the first succe...  ...
4                                               None  ...

                   date_utc   date_unix                 date_local  \
0  2006-03-24T22:30:00.000Z  1143239400  2006-03-25T10:30:00+12:00
1  2007-03-21T01:10:00.000Z  1174439400  2007-03-21T13:10:00+12:00
2  2008-08-03T03:34:00.000Z  1217734440  2008-08-03T15:34:00+12:00
3  2008-09-28T23:15:00.000Z  1222643700  2008-09-28T11:15:00+12:00
4  2009-07-13T03:35:00.000Z  1247456100  2009-07-13T15:35:00+12:00

  date_precision upcoming                                              cores  \
0           hour    False  [{'core': '5e9e289df35918033d3b2623', 'flight'...
1           hour    False  [{'core': '5e9e289ef35918416a3b2624', 'flight'...
2           hour    False  [{'core': '5e9e289ef3591814873b2625', 'flight'...
3           hour    False  [{'core': '5e9e289ef3591855dc3b2626', 'flight'...
4           hour    False  [{'core': '5e9e289ef359184f103b2627', 'flight'...

  auto_update    tbd  launch_library_id                        id
0        True  False               None  5eb87cd9ffd86e000604b32a
1        True  False               None  5eb87cdaffd86e000604b32b
2        True  False               None  5eb87cdbffd86e000604b32c
3        True  False               None  5eb87cdbffd86e000604b32d
4        True  False               None  5eb87cdcffd86e000604b32e

[5 rows x 27 columns]
Index(['fairings', 'links', 'static_fire_date_utc', 'static_fire_date_unix',
       'net', 'window', 'rocket', 'success', 'failures', 'details', 'crew',
       'ships', 'capsules', 'payloads', 'launchpad', 'flight_number', 'name',
       'date_utc', 'date_unix', 'date_local', 'date_precision', 'upcoming',
       'cores', 'auto_update', 'tbd', 'launch_library_id', 'id'],
      dtype='object')

In [8]:
df['name']

0                   FalconSat
1                     DemoSat
2                 Trailblazer
3                      RatSat
4                    RazakSat
                ...
200             Transporter-6
201                     TTL-1
202    WorldView Legion 1 & 2
203       Viasat-3 & Arcturus
204            O3b mPower 3.4
Name: name, Length: 205, dtype: object

In [9]:
df = df[['name','date_utc','success','details','rocket']]

In [10]:
print(df)

                       name                  date_utc success  \
0                 FalconSat  2006-03-24T22:30:00.000Z   False
1                   DemoSat  2007-03-21T01:10:00.000Z   False
2               Trailblazer  2008-08-03T03:34:00.000Z   False
3                    RatSat  2008-09-28T23:15:00.000Z    True
4                  RazakSat  2009-07-13T03:35:00.000Z    True
..                      ...                       ...     ...
200           Transporter-6  2022-12-01T00:00:00.000Z    None
201                   TTL-1  2022-12-01T00:00:00.000Z    None
202  WorldView Legion 1 & 2  2022-12-01T00:00:00.000Z    None
203     Viasat-3 & Arcturus  2022-12-01T00:00:00.000Z    None
204          O3b mPower 3.4  2022-12-01T00:00:00.000Z    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket
0    5e9d0d95eda69955f709d1eb
1    5e9d0d95eda69955f709d1eb
2    5e9d0d95eda69955f709d1eb
3    5e9d0d95eda69955f709d1eb
4    5e9d0d95eda69955f709d1eb
..                        ...
200  5e9d0d95eda69973a809d1ec
201  5e9d0d95eda69973a809d1ec
202  5e9d0d95eda69973a809d1ec
203  5e9d0d95eda69974db09d1ed
204  5e9d0d95eda69973a809d1ec

[205 rows x 5 columns]

● Convert date_utc to datetime and extract the year

In [12]:
df.loc[:, 'date_utc'] = pd.to_datetime(df['date_utc'])

In [13]:
print(df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket
0    5e9d0d95eda69955f709d1eb
1    5e9d0d95eda69955f709d1eb
2    5e9d0d95eda69955f709d1eb
3    5e9d0d95eda69955f709d1eb
4    5e9d0d95eda69955f709d1eb
..                        ...
200  5e9d0d95eda69973a809d1ec
201  5e9d0d95eda69973a809d1ec
202  5e9d0d95eda69973a809d1ec
203  5e9d0d95eda69974db09d1ed
204  5e9d0d95eda69973a809d1ec

[205 rows x 5 columns]

In [14]:
print(type(df['date_utc'][0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [16]:
df.loc[:,'year'] = df['date_utc'].dt.year

In [18]:
df['year']

0      2006
1      2007
2      2008
3      2008
4      2009
       ...
200    2022
201    2022
202    2022
203    2022
204    2022
Name: year, Length: 205, dtype: int32

In [19]:
print(df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year
0    5e9d0d95eda69955f709d1eb  2006
1    5e9d0d95eda69955f709d1eb  2007
2    5e9d0d95eda69955f709d1eb  2008
3    5e9d0d95eda69955f709d1eb  2008
4    5e9d0d95eda69955f709d1eb  2009
..                        ...   ...
200  5e9d0d95eda69973a809d1ec  2022
201  5e9d0d95eda69973a809d1ec  2022
202  5e9d0d95eda69973a809d1ec  2022
203  5e9d0d95eda69974db09d1ed  2022
204  5e9d0d95eda69973a809d1ec  2022

[205 rows x 6 columns]

Step 2: Load Rocket Metadata
● Use https://api.spacexdata.com/v4/rockets
● Extract id, name, type, active, and stages

In [25]:
import requests

rocket_url = " https://api.spacexdata.com/v4/rockets"
rocket_data = requests.get(rocket_url).json()

In [26]:
print(type(rocket_data))
print(rocket_data[0])

<class 'list'>
{'height': {'meters': 22.25, 'feet': 73}, 'diameter': {'meters': 1.68, 'feet': 5.5}, 'mass': {'kg': 30146, 'lb': 66460}, 'first_stage': {'thrust_sea_level': {'kN': 420, 'lbf': 94000}, 'thrust_vacuum': {'kN': 480, 'lbf': 110000}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 44.3, 'burn_time_sec': 169}, 'second_stage': {'thrust': {'kN': 31, 'lbf': 7000}, 'payloads': {'composite_fairing': {'height': {'meters': 3.5, 'feet': 11.5}, 'diameter': {'meters': 1.5, 'feet': 4.9}}, 'option_1': 'composite fairing'}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 3.38, 'burn_time_sec': 378}, 'engines': {'isp': {'sea_level': 267, 'vacuum': 304}, 'thrust_sea_level': {'kN': 420, 'lbf': 94000}, 'thrust_vacuum': {'kN': 480, 'lbf': 110000}, 'number': 1, 'type': 'merlin', 'version': '1C', 'layout': 'single', 'engine_loss_max': 0, 'propellant_1': 'liquid oxygen', 'propellant_2': 'RP-1 kerosene', 'thrust_to_weight': 96}, 'landing_legs': {'number': 0, 'material': None}, 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}

In [27]:
#convert this into dataframe
import pandas as pd
rocket_df = pd.DataFrame(rocket_data)

In [29]:
print(df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year
0    5e9d0d95eda69955f709d1eb  2006
1    5e9d0d95eda69955f709d1eb  2007
2    5e9d0d95eda69955f709d1eb  2008
3    5e9d0d95eda69955f709d1eb  2008
4    5e9d0d95eda69955f709d1eb  2009
..                        ...   ...
200  5e9d0d95eda69973a809d1ec  2022
201  5e9d0d95eda69973a809d1ec  2022
202  5e9d0d95eda69973a809d1ec  2022
203  5e9d0d95eda69974db09d1ed  2022
204  5e9d0d95eda69973a809d1ec  2022

[205 rows x 6 columns]

In [30]:
rocket_df = rocket_df[['id', 'name', 'type', 'active', 'stages']]
print(df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year
0    5e9d0d95eda69955f709d1eb  2006
1    5e9d0d95eda69955f709d1eb  2007
2    5e9d0d95eda69955f709d1eb  2008
3    5e9d0d95eda69955f709d1eb  2008
4    5e9d0d95eda69955f709d1eb  2009
..                        ...   ...
200  5e9d0d95eda69973a809d1ec  2022
201  5e9d0d95eda69973a809d1ec  2022
202  5e9d0d95eda69973a809d1ec  2022
203  5e9d0d95eda69974db09d1ed  2022
204  5e9d0d95eda69973a809d1ec  2022

[205 rows x 6 columns]

In [32]:
rocket_df.rename(columns={'id':'rocket'},inplace=True)

In [33]:
print(df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year
0    5e9d0d95eda69955f709d1eb  2006
1    5e9d0d95eda69955f709d1eb  2007
2    5e9d0d95eda69955f709d1eb  2008
3    5e9d0d95eda69955f709d1eb  2008
4    5e9d0d95eda69955f709d1eb  2009
..                        ...   ...
200  5e9d0d95eda69973a809d1ec  2022
201  5e9d0d95eda69973a809d1ec  2022
202  5e9d0d95eda69973a809d1ec  2022
203  5e9d0d95eda69974db09d1ed  2022
204  5e9d0d95eda69973a809d1ec  2022

[205 rows x 6 columns]

In [34]:
merged_df = pd.merge(df,rocket_df,on='rocket',how='left')

In [35]:
print(merged_df)

                     name_x                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year        name_y    type  active  stages
0    5e9d0d95eda69955f709d1eb  2006      Falcon 1  rocket   False       2
1    5e9d0d95eda69955f709d1eb  2007      Falcon 1  rocket   False       2
2    5e9d0d95eda69955f709d1eb  2008      Falcon 1  rocket   False       2
3    5e9d0d95eda69955f709d1eb  2008      Falcon 1  rocket   False       2
4    5e9d0d95eda69955f709d1eb  2009      Falcon 1  rocket   False       2
..                        ...   ...           ...     ...     ...     ...
200  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
201  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
202  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
203  5e9d0d95eda69974db09d1ed  2022  Falcon Heavy  rocket    True       2
204  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2

[205 rows x 10 columns]

In [36]:
merged_df.rename(columns={'name_x':'launch_name'},inplace=True)
merged_df.rename(columns={'name_y':'rocket_name'},inplace=True)

In [37]:
print(merged_df.columns)
print(merged_df.head())

Index(['launch_name', 'date_utc', 'success', 'details', 'rocket', 'year',
       'rocket_name', 'type', 'active', 'stages'],
      dtype='object')
   launch_name                  date_utc success  \
0    FalconSat 2006-03-24 22:30:00+00:00   False
1      DemoSat 2007-03-21 01:10:00+00:00   False
2  Trailblazer 2008-08-03 03:34:00+00:00   False
3       RatSat 2008-09-28 23:15:00+00:00    True
4     RazakSat 2009-07-13 03:35:00+00:00    True

                                             details  \
0   Engine failure at 33 seconds and loss of vehicle
1  Successful first stage burn and transition to ...
2  Residual stage 1 thrust led to collision betwe...
3  Ratsat was carried to orbit on the first succe...
4                                               None

                     rocket  year rocket_name    type  active  stages
0  5e9d0d95eda69955f709d1eb  2006    Falcon 1  rocket   False       2
1  5e9d0d95eda69955f709d1eb  2007    Falcon 1  rocket   False       2
2  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2
3  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2
4  5e9d0d95eda69955f709d1eb  2009    Falcon 1  rocket   False       2

Step 4: Add Simulated Country Information
● Add a new column country and randomly assign one of these values:
['USA', 'Russia', 'India', 'China', 'France']

In [38]:
import random
countries = ['USA', 'Russia', 'India', 'China', 'France']

merged_df['country'] = [random.choice(countries) for _ in range(len(merged_df))]

In [39]:
print(merged_df[['launch_name', 'country']].head())

   launch_name country
0    FalconSat   India
1      DemoSat   India
2  Trailblazer  Russia
3       RatSat  France
4     RazakSat     USA

In [40]:
print(merged_df)

                launch_name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket  year   rocket_name    type  active  stages  \
0    5e9d0d95eda69955f709d1eb  2006      Falcon 1  rocket   False       2
1    5e9d0d95eda69955f709d1eb  2007      Falcon 1  rocket   False       2
2    5e9d0d95eda69955f709d1eb  2008      Falcon 1  rocket   False       2
3    5e9d0d95eda69955f709d1eb  2008      Falcon 1  rocket   False       2
4    5e9d0d95eda69955f709d1eb  2009      Falcon 1  rocket   False       2
..                        ...   ...           ...     ...     ...     ...
200  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
201  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
202  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2
203  5e9d0d95eda69974db09d1ed  2022  Falcon Heavy  rocket    True       2
204  5e9d0d95eda69973a809d1ec  2022      Falcon 9  rocket    True       2

    country
0     India
1     India
2    Russia
3    France
4       USA
..      ...
200  Russia
201   China
202  Russia
203  Russia
204   China

[205 rows x 11 columns]

In [41]:
import sqlite3

conn = sqlite3.connect("spacex.db")

In [43]:
merged_df.to_sql("launches", conn, if_exists="replace", index=False)

205

In [44]:
import pandas as pd

pd.read_sql("SELECT COUNT(*) FROM launches", conn)

   COUNT(*)
0       205

In [ ]:
Step 6: Run SQL Queries on the Data to analyze
1. Launches by Country
2. Which year had the highest number of launches?
3. Top 5 Missions by Launch Count

In [45]:
import pandas as pd

query1 = """
SELECT country, COUNT(*) as total_launches
FROM launches
GROUP BY country
ORDER BY total_launches DESC;
"""

pd.read_sql(query1, conn)

  country  total_launches
0     USA              49
1   India              48
2   China              40
3  France              35
4  Russia              33

In [47]:
#Which year had the highest number of launchesquery2 = """
query2 = """ SELECT year, COUNT(*) as total_launches
FROM launches
GROUP BY year
ORDER BY total_launches DESC
LIMIT 1;
"""

print(pd.read_sql(query2, conn))

   year  total_launches
0  2022              62

In [48]:
# Top 5 Missions by Launch Count
query3 = """
SELECT launch_name, COUNT(*) as total_launches
FROM launches
GROUP BY launch_name
ORDER BY total_launches DESC
LIMIT 5;
"""

print(pd.read_sql(query3, conn))

                 launch_name  total_launches
0  ispace Mission 1 & Rashid               1
1                       ZUMA               1
2     WorldView Legion 1 & 2               1
3        Viasat-3 & Arcturus               1
4                    USSF-44               1